<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\VardyParty.Playback\VardyParty.Playback.csproj" />
    <ProjectReference Include="..\..\VardyParty.Ports\VardyParty.Ports.csproj" />
    <ProjectReference Include="..\..\VardyParty.Streaming\VardyParty.Streaming.csproj" />
  </ItemGroup>
</Project>
