<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Version.props" />

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>VardyParty.Streaming</RootNamespace>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<AssemblyVersion>$(ApplicationVersion)</AssemblyVersion>
		<FileVersion>$(ApplicationDisplayVersion).0</FileVersion>
		<InformationalVersion>$(ApplicationDisplayVersion)</InformationalVersion>
		<UseMonoRuntime>false</UseMonoRuntime>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Reactive" Version="6.1.0" />
		<PackageReference Include="VardyParty.LocalService.Client" Version="0.1.23" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\VardyParty.Kernel\VardyParty.Kernel.csproj" />
		<ProjectReference Include="..\VardyParty.Ports\VardyParty.Ports.csproj" />
		<ProjectReference Include="..\VardyParty.Catalog\VardyParty.Catalog.csproj" />
	</ItemGroup>

</Project>
