<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Version.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>VardyParty</RootNamespace>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<AssemblyVersion>$(ApplicationVersion)</AssemblyVersion>
		<FileVersion>$(ApplicationDisplayVersion).0</FileVersion>
		<InformationalVersion>$(ApplicationDisplayVersion)</InformationalVersion>
		<UseMonoRuntime>false</UseMonoRuntime>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\VardyParty.Kernel\VardyParty.Kernel.csproj" />
	</ItemGroup>

</Project>
